services:
  ros2:
    build:
      context: ../..
      dockerfile: .docker/ubuntu_desktop/Dockerfile    

    container_name: robind_lab

    network_mode: host
    ipc: host

    stdin_open: true
    tty: true

    volumes:
      - ../../ros2_ws:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw

    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      LIBGL_ALWAYS_SOFTWARE: 1
      XAUTHORITY: /root/.Xauthority