services:
  ros2:
    build:
      context: ../..
      dockerfile: .docker/ubuntu_desktop/Dockerfile    

    container_name: ros2_dev_lab

    network_mode: host
    ipc: host

    stdin_open: true
    tty: true

    volumes:
      - ../../ros2_ws:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      LIBGL_ALWAYS_SOFTWARE: 1

    #devices:
    #  - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/rplidar
    